### ISSUE TITLE
failing install glade

### ISSUE THREAD

**Issue by Ukunsun** [gtk2hs/glade#4]
Hi!
Try to install package glade
The Glorious Glasgow Haskell Compilation System, version 7.10.2
glib-0.13.2.1
gtk-0.13.9
cairo-0.13.1.0
gio-0.13.1.0
pango-0.13.1.0
I have this output: $ sudo cabal install glade

Resolving dependencies...
Configuring cairo-0.12.5.3...
Configuring glib-0.12.5.4...
Failed to install cairo-0.12.5.3
Build log (~/.cabal/logs/cairo-0.12.5.3.log ):
Failed to install glib-0.12.5.4
Build log ( !/.cabal/logs/glib-0.12.5.4.log ):
cabal: Error: some packages failed to install:
cairo-0.12.5.3 failed during the configure step. The exception was:
user error ('/usr/local/bin/ghc' exited with an error:

/tmp/cabal-tmp-13145/cairo-0.12.5.3/SetupWrapper.hs:91:17:
Ambiguous occurrence ‘die’
It could refer to either ‘Distribution.Simple.Utils.die’,
imported from ‘Distribution.Simple.Utils’ at
/tmp/cabal-tmp-13145/cairo-0.12.5.3/SetupWrapper.hs:8:1-32
or ‘System.Exit.die’,
imported from ‘System.Exit’ at
/tmp/cabal-tmp-13145/cairo-0.12.5.3/SetupWrapper.hs:21:1-18
)
gio-0.12.5.3 depends on glib-0.12.5.4 which failed to install.
glade-0.12.5.0 depends on glib-0.12.5.4 which failed to install.
glib-0.12.5.4 failed during the configure step. The exception was:
user error ('/usr/local/bin/ghc' exited with an error:

/tmp/cabal-tmp-13146/glib-0.12.5.4/SetupWrapper.hs:91:17:
Ambiguous occurrence ‘die’
It could refer to either ‘Distribution.Simple.Utils.die’,
imported from ‘Distribution.Simple.Utils’ at
/tmp/cabal-tmp-13146/glib-0.12.5.4/SetupWrapper.hs:8:1-32
or ‘System.Exit.die’,
imported from ‘System.Exit’ at
/tmp/cabal-tmp-13146/glib-0.12.5.4/SetupWrapper.hs:21:1-18
)
gtk-0.12.5.7 depends on glib-0.12.5.4 which failed to install.
pango-0.12.5.3 depends on glib-0.12.5.4 which failed to install.

**Comment by nikolasburk** [comment]
I have the same issue! Has it been resolved yet?

**Comment by cmaeder** [comment]
I've got a patch for this (ghc-7.10.2) based on #3 https://github.com/cmaeder/glade.
Could someone `git merge --squash` my fork, call `cabal sdist` and upload the resulting glade-0.13.0.tar.gz to hackage?

**Comment by cmaeder** [comment]
@hamishmack could you make a new release (as mentioned above)? I'm reluctant to make a PR since there is no reaction already for #3

**Comment by cmaeder** [comment]
@hamishmack Do you mind if I make an upload to hackage? (Since there are only very few people that might use glade it would do not harm much.)

**Comment by ivanperez-keera** [comment]
I just hit this bug. I can confirm that @cmaeder's solution lets me compile and execute my app, and it seems to function normally.  (However, I have not personally verified the changes to the code itself).

**Comment by hamishmack** [comment]
Sorry @cmaeder, I was going to upload this to hackage and forgot.  I have uploaded it now.  Thanks for fixing it.

**Comment by ivanperez-keera** [comment]
Sorry for commenting on a closed issue, but I'm trying to put something on a PPA and `glade`'s constraints mean that I have to bundle a lot of libraries with my app. Do the lower-bound constraints on `glib` and `gtk` really need to be so strict? Would `> 0.13` be enough?

Does the lower-bound constraint on `Cabal` need to be 1.24? Can it be 1.22?

**Comment by cmaeder** [comment]
Cabal 1.24 is required (as for the newer gtk packages).

**Comment by ivanperez-keera** [comment]
I relaxed the requirements on `gtk` and `glib` and my app compiles and works fine. Couldn't do the same thing with `Cabal` though. So, yes, you are right.
